version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    privileged: true
    hostname: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
      - 25672:25672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
  