version: '3.6'

services:

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    volumes: 
      - /home/mysql/config:/etc/mysql
      - /home/mysql/data-files:/var/lib/mysql-files
      - /home/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
