version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes: 
      - /data/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
