version: '3.1'

services:

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - /data/redis/config/redis.conf:/etc/redis/redis.conf
      - /data/redis/data:/data
    command: redis-server /etc/redis/redis.conf
