version: '3.8'

services:

  zookeeper1:
    image: zookeeper
    restart: always
    hostname: zookeeper1
    ports: 
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    image: zookeeper
    restart: always
    hostname: zookeeper2
    ports: 
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper3:2888:3888
      
  zookeeper3:
    image: zookeeper
    restart: always
    hostname: zookeeper3
    ports: 
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=0.0.0.0:2888:3888

  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    ports: 
      - 9092:9092
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181

  kafka2:
    image: wurstmeister/kafka
    hostname: kafka2
    ports: 
      - 9093:9092
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - 9000:9000
    command: -Dpidfile.path=/dev/null
    environment:
      ZK_HOSTS: zookeeper1:2181
      APPLICATION_SECRET: random-secret
